blog/urls.py
# -*- coding: utf-8 -*-
"""
  :synopsis: urls for the blog app.

.. module: blog.urls
.. author: Chris Bartlett <chris.bartlett@therealbuzzgroup.com>
"""
from django.urls import path, re_path

from blog.views import BlogPostView, BlogPostListView


urlpatterns = [
    path('', BlogPostListView.as_view(), name='list'),
    re_path(r'(?P<slug>[\w-]+)/$', BlogPostView.as_view(), name='post'),
]

home/urls.py
# -*- coding: utf-8 -*-
"""
  :synopsis: urls for the home app.

.. module: home.urls
.. author: Chris Bartlett <bartlett.christopher.p@gmail.com>
"""
from django.urls import path

from home.views import EnquiryView, LandingView


urlpatterns = [
    path('', LandingView.as_view(), name='landing'),
    path('contact-us', EnquiryView.as_view(), name='enquiry'),
]

project/urls.py
"""Project URL Configuration."""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('blogs/', include(('blog.urls', 'blog'), namespace='blog')),
]

common/mixins/models/enabled.py
# -*- coding: utf-8 -*-
"""
  :synopsis: mixin to add enabled boolean flag to object.

.. module:: common.mixins.models.enabled
.. author:: Chris Bartlett <chris.bartlett@therealbuzzgroup.com>
"""
from django.db import models
from django.utils.translation import ugettext_lazy as _


class EnabledMixin(models.Model):
    """Mixin to add enabled boolean field to object."""

    enabled = models.BooleanField(
        verbose_name=_('Enabled?'),
        default=True,
    )

    class Meta:
        """Metaclass for EnabledMixin."""

        abstract = True

    def enable(self, commit=True):
        """
        Enable this object.

        :param commit
        :type commit: bool
        """
        self.enabled = True

        if commit:
            self.save(update_fields=['enabled'])

    def disable(self, commit=True):
        """Disable this object."""
        self.enabled = False

        if commit:
            self.save(update_fields=['enabled'])

common/mixins/models/timestamp.py
# -*- coding: utf-8 -*-
"""
  :synopsis: mixin to add time stamping fields to object.

.. module:: common.mixins.models.timestamp
.. author:: Chris Bartlett <chris.bartlett@therealbuzzgroup.com>
"""
from django.db import models
from django.utils.translation import ugettext_lazy as _


class TimeStampMixin(models.Model):
    """Mixin to add created and modified timestamps."""

    created = models.DateTimeField(
        verbose_name=_('Date object created'),
        editable=False,
        auto_now_add=True,
        help_text=_('Date and time that this object was created.')
    )
    modified = models.DateTimeField(
        verbose_name=_('Date object last modified'),
        editable=False,
        auto_now=True
    )

    class Meta:
        """Metadata for TimeStampMixin."""

        abstract = True

common/templates/common/banner.html
<div class="banner__logo">
    -/+
</div>

<span>
    Negative to Positive
</span>

common/templates/common/breadcrumbs.html
{% for url, label in breadcrumbs %}
        {% ifnotequal forloop.counter breadcrumbs_total %}
            <a class="breadcrumbs__item" href="{{ url }}">{{ label|safe }}</a>
        {% else %}
            <span class="breadcrumbs__item">{{ label|safe }}</span>
        {% endifnotequal %}
        {% if not forloop.last %}
            <span class="breadcrumbs__item">&gt;</span>
        {% endif %}
{% endfor %}

common/templates/common/navigation.html
{% block navigation %}
        <a class="nav__url" href="{% url 'home:landing' %}">Home</a>
        <a class="nav__url" href="{% url 'blog:list' %}">Blogs</a>
        <a class="nav__url" href="{% url 'home:enquiry' %}">Contact us</a>
{% endblock navigation %}